<!--

JavaScript try and catch

The try statement allows you to define a block of code to be tested for errors
 while it is being executed.

The catch statement allows you to define a block of code to be executed, 
if an error occurs in the try block.

The JavaScript statements try and catch come in pairs:

try {
  Block of code to try
}
catch(err) {
  Block of code to handleÂ errors
}

--->

<p>please input a number between 5 and 10:</p>

<input id="demo" type="text">
<button type="button" onclick="myFunction()">Test Input</button>
<p id="p01"></p>

<script>
    function myFunction() {
        const message= document.getElementById("p01");
        message.innerHTML ="";
        let x = document.getElementById("demo").value;
        try {
            if(x.trim() =="") throw "empty";
            if (isNaN(x)) throw "not a number";
            x = Number(x);
            if (x < 5) throw "two low"; 
            if (x > 10) throw "too high";
        }

        catch (err) {
            message.innerHTML = "input is " + err ;
        }
    }

</script>